#---------------------------------------------------#
## 配置文件需要放置在 $HOME/.config/clash/*.yaml

## 这份文件是clashX的基础配置文件，请尽量新建配置文件进行修改。
## ！！！只有这份文件的端口设置会随ClashX启动生效

## 如果您不知道如何操作，请参阅 官方Github文档 https://github.com/Dreamacro/clash/blob/dev/README.md
#---------------------------------------------------#

# (HTTP and SOCKS5 in one port)
mixed-port: 7890
# RESTful API for clash
external-controller: 127.0.0.1:9090
allow-lan: false
mode: rule
log-level: info

proxies:

proxy-groups:  
  - name: PROXY
    type: select
    proxies:
      - DIRECT
      - Cherry
      - XFTLD
      - NanoPort
  - name: Cherry
    type: select
    use:
      - cherry
  - name: XFTLD
    type: select
    use:
      - XFTLD
  - name: NanoPort
    type: select
    use:
      - NanoPort
  # TODO add subscription link here

proxy-providers:
  cherry:
    type: http
    url: https://api1.cherrylink.me/sub?target=clash&url=https://cherryvpn.net/link/uuDbYai1EOLI4kzJ?sub=2
    interval: 172800
    path: ./profiles/subscriptions/Cherry.yaml
    health-check:
      enable: true
      interval: 3600
      # lazy: true
      url: http://www.gstatic.com/generate_204
  XFTLD:
    type: http
    url: https://sub.xeton.dev/sub?target=clash&url=https%3A%2F%2Fdy.xftld.xyz%2Fapi%2Fv1%2Fclient%2Fsubscribe%3Ftoken%3D52be752db95308d1669f3e271619d21e&insert=false&config=https%3A%2F%2Fraw.githubusercontent.com%2FACL4SSR%2FACL4SSR%2Fmaster%2FClash%2Fconfig%2FACL4SSR_Online.ini
    interval: 172800
    path: ./profiles/subscriptions/XFTLD.yaml
    health-check:
      enable: true
      interval: 3600
      # lazy: true
      url: http://www.gstatic.com/generate_204
  NanoPort:
    type: http
    url: https://sub.xeton.dev/sub?target=clash&new_name=true&url=https%3A%2F%2Fsubv5.nanoport.xyz%2Fapi%2Fv1%2Fclient%2Fsubscribe%3Ftoken%3D5d98ac512e48006d875ae89253762089&insert=false&config=https%3A%2F%2Fraw.githubusercontent.com%2FACL4SSR%2FACL4SSR%2Fmaster%2FClash%2Fconfig%2FACL4SSR_Online.ini
    interval: 172800
    path: ./profiles/subscriptions/NanoPort.yaml
    health-check:
      enable: true
      interval: 3600
      # lazy: true
      url: http://www.gstatic.com/generate_204
    

  # TODO add subscription link here

rule-providers:
  proxy:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/r1cebucket/vpn/main/rules/clash_proxy.conf
    path: ./profiles/rules/proxy.yaml
    interval: 172800
  direct:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/r1cebucket/vpn/main/rules/clash_direct.conf
    path: ./profiles/rules/direct.yaml
    interval: 172800


rules:

  - RULE-SET,proxy,PROXY
  - RULE-SET,direct,DIRECT

  # - DOMAIN-SUFFIX,google.com,PROXY
  # - DOMAIN-KEYWORD,google,PROXY
  # - DOMAIN,google.com,PROXY
  # - DOMAIN-SUFFIX,ad.com,REJECT

  - GEOIP,CN,DIRECT
  - MATCH,PROXY
