# reject domains
[reject]
"domain_suffix" = [
    # analytic
    "app-measurement.com",
    "appsflyer.com",
    "google-analytics.com",
    "openinstall.io",

    # ads
    "amazon-adsystem.com",
    "doubleclick.net",
    "rubiconproject.com",
    "adservice.google.com",
    "wwads.cn",
    "ads.inmobi.com",
    "tappx.com",
    "criteo.com",
    "pubmatic.com",
    "smaato.net",
    "adsappier.com",
    "appier.net",
    "appiersig.com",
    "inner-active.mobi",

    # Baidu
    "tieba-ares.cdn.bcebos.com",
]
