name: Auto Generate and Release

on:
  push:
    branches: [ main ] # branch
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'
          check-latest: true

      - name: Run Go program
        run: go run main.go

      - name: Generate release timestamp
        id: timestamp
        run: echo "release_time=$(date +'%Y%m%d_%H%M%S')" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: release_${{ steps.timestamp.outputs.release_time }}
          name: Release ${{ steps.timestamp.outputs.release_time }}
          draft: false
          prerelease: false
          files: |
            rules/*